baseURL = "https://thedarthmell.github.io/"
languageCode = "en-us"
title = "Mel Yurttas"
theme = "blowfish"

[params]
  defaultTheme = "dark"
  colorScheme = "blowfish"


[languages.en.params.author]
  name = "Mel Yurttas"
  image = "ben.jpg"
  headline = "Game Designer | Content Creator | Mentor"
  bio = "Building worlds in engines and communities on social media."
  links = [
    { icon = "instagram", link = "https://instagram.com/thedarthmel" },
    { icon = "youtube", link = "https://youtube.com/@thedarthmel3283" },
    { icon = "linkedin", link = "https://www.linkedin.com/in/meltem-yurtta%C5%9F/" },
    { icon = "itch-io", link = "https://itch.io/profile/thedarthmel" }
  ]


[languages.en.params.home.profile]
  enable = true
  showName = true
  showBio = true
  showLinks = true

[languages.en.params.home]
  showRecent = true
  section = "portfolio" 

[menu]
  # --- 1. PROJECTS ---
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/portfolio/"
    weight = 10

  [[menu.main]]
    parent = "projects"
    name = "All Games (Itch.io)"
    url = "/portfolio/games/"
    weight = 1

  [[menu.main]]
    parent = "projects"
    identifier = "prototypes"
    name = "Prototypes & Jams"
    url = "/portfolio/prototypes/"
    weight = 2

  # --- 2. CONTENT (Çatı Menü) ---
  [[menu.main]]
    identifier = "content-main"
    name = "Content"
    url = "/blog/"   # Ana tıklamada Blog'a veya genel listeye gider
    weight = 20

  # 2.1 Blog (Articles) - YENİ SEKME
  [[menu.main]]
    parent = "content-main"
    identifier = "blog-posts"
    name = "Blog (Articles)"
    url = "/blog/"
    weight = 1

  # 2.2 YouTube (Artık ayrı klasörde)
  [[menu.main]]
    parent = "content-main"
    identifier = "youtube"
    name = "YouTube (Deep Dive)"
    url = "/videos/"    # DİKKAT: Artık /blog/videos değil, direkt /videos/
    weight = 2

  # 2.3 Shorts
  [[menu.main]]
    parent = "content-main"
    identifier = "shorts"
    name = "Shorts & Tips"
    url = "/reels/"
    weight = 3

  # --- 3. COMMUNITY ---
  [[menu.main]]
    identifier = "community"
    name = "Community"
    url = "/events/"
    weight = 30

  [[menu.main]]
    parent = "community"
    identifier = "education"
    name = "Education"
    url = "/education/"
    weight = 1

  [[menu.main]]
    parent = "community"
    identifier = "talks"
    name = "Talks & Mentorship"
    url = "/events/"
    weight = 2

  # --- 4. LIBRARY ---
  [[menu.main]]
    identifier = "library"
    name = "Library"
    url = "/reviews/"
    weight = 40
    
  [[menu.main]]
    parent = "library"
    identifier = "favorites"
    name = "Mel's Favorites"
    url = "/library/favorites/" 
    weight = 2

  # --- 5. ABOUT ---
  [[menu.main]]
    identifier = "about"
    name = "About & CV"
    url = "/about/"
    weight = 50

    [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true