baseURL = "https://thedarthmell.github.io/"
languageCode = "en-us"
title = "Mel Yurttas"
theme = "blowfish"

[params]
  defaultTheme = "dark"
  colorScheme = "blowfish"


[languages.en.params.author]
  name = "Mel Yurttas"
  image = "ben.jpg"
  headline = "Game Designer | Content Creator | Mentor"
  bio = "Building worlds in engines and communities on social media."
  links = [
    { icon = "instagram", link = "https://instagram.com/thedarthmel" },
    { icon = "youtube", link = "https://youtube.com/@thedarthmel3283" },
    { icon = "linkedin", link = "https://www.linkedin.com/in/meltem-yurtta%C5%9F/" },
    { icon = "itch-io", link = "https://itch.io/profile/thedarthmel" }
  ]


[languages.en.params.home.profile]
  enable = true
  showName = true
  showBio = true
  showLinks = true

[languages.en.params.home]
  showRecent = true
  section = "portfolio" 

[menu]
  # --- 1. GAMES (The Core) ---
  [[menu.main]]
    identifier = "games"
    name = "GAMES"
    url = "/games/"
    weight = 10

  [[menu.main]]
    parent = "games"
    identifier = "pro-work"
    name = "Professional Work"
    url = "/games/professional/"
    weight = 1

  [[menu.main]]
    parent = "games"
    identifier = "prototypes"
    name = "Prototypes & Jams"
    url = "/games/prototypes/"
    weight = 2

  # --- 2. CONTENT (Media Hub) ---
  [[menu.main]]
    identifier = "content-hub"
    name = "CONTENT"
    url = "/creations/"
    weight = 20

  [[menu.main]]
    parent = "content-hub"
    identifier = "essays"
    name = "Essays & Deep Dives"
    url = "/creations/essays/"
    weight = 1

  [[menu.main]]
    parent = "content-hub"
    identifier = "shorts"
    name = "Shorts & Tips"
    url = "/creations/shorts/"
    weight = 2

  [[menu.main]]
    parent = "content-hub"
    identifier = "blog"
    name = "Blog"
    url = "/creations/blog/"
    weight = 3

  # --- 3. TALKS (Authority) ---
  [[menu.main]]
    identifier = "talks"
    name = "TALKS"
    url = "/talks/"
    weight = 30

  [[menu.main]]
    parent = "talks"
    identifier = "lectures"
    name = "Guest Lectures & Panels"
    url = "/talks/lectures/"
    weight = 1

  [[menu.main]]
    parent = "talks"
    identifier = "mentorship"
    name = "Mentorship"
    url = "/talks/mentorship/"
    weight = 2

  # --- 4. LIBRARY (Curator) ---
  [[menu.main]]
    identifier = "library"
    name = "LIBRARY"
    url = "/library/"
    weight = 40

  [[menu.main]]
    parent = "library"
    identifier = "resources"
    name = "Dev Resources"
    url = "/library/resources/"
    weight = 1

  [[menu.main]]
    parent = "library"
    identifier = "favorites"
    name = "Melâ€™s Favorites"
    url = "/library/favorites/"
    weight = 2

  # --- 5. ABOUT (Persona) ---
  [[menu.main]]
    identifier = "about"
    name = "ABOUT"
    url = "/about/"
    weight = 50